name = "OptimalEstimationProject"
uuid = "3d1b1f1a-7e11-45f0-8494-bf27496a6cf9"
authors = ["Grant Hecht"]
version = "0.1.0"

[deps]
AstroTime = "c61b5328-d09d-5e37-a9a8-0eb41c39009c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
EarthOrientation = "732a3c5d-d6c0-58bc-adb1-1b51709a25e2"
Heuristics = "6acb60cf-2fd4-4316-b77c-a68f9bfdd616"
IndirectCoStateInit = "21a510a3-10c0-42ba-9160-0f1f186b68a8"
IndirectShooting = "552ddee8-f2c8-412c-9a93-d98e9622e980"
IndirectTrajOpt = "99e47ffd-a99c-4d17-8b51-d4481b168213"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SuiteSparse = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
StatsBase = "0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
